runtime: python37
env: standard
instance_class: F2
automatic_scaling:
  max_concurrent_requests: 16
  min_pending_latency: 300ms
  max_pending_latency: 300ms
#entrypoint: gunicorn -b :$PORT main:app
#
#runtime_config:
#  python_version: 3
#
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10
